// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz9OnhdjUWbehhV5tZ-zDgslsdaRX-UkY',
    appId: '1:734665714900:web:a4991b39d837ba87455f41',
    messagingSenderId: '734665714900',
    projectId: 'yesloyalty-97b09',
    authDomain: 'yesloyalty-97b09.firebaseapp.com',
    storageBucket: 'yesloyalty-97b09.appspot.com',
    measurementId: 'G-J9B4XGX05E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2Y4ytcikJyJMPKhY9ETWgJZfCCBqfpA',
    appId: '1:734665714900:android:1c3195303c11eca4455f41',
    messagingSenderId: '734665714900',
    projectId: 'yesloyalty-97b09',
    storageBucket: 'yesloyalty-97b09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLf8gQbIDqWXrVtzBa9zpkU2Hieu3gdCA',
    appId: '1:734665714900:ios:3aeefd5ddca1eb7b455f41',
    messagingSenderId: '734665714900',
    projectId: 'yesloyalty-97b09',
    storageBucket: 'yesloyalty-97b09.appspot.com',
    iosBundleId: 'com.example.yesLoyality',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLf8gQbIDqWXrVtzBa9zpkU2Hieu3gdCA',
    appId: '1:734665714900:ios:3aeefd5ddca1eb7b455f41',
    messagingSenderId: '734665714900',
    projectId: 'yesloyalty-97b09',
    storageBucket: 'yesloyalty-97b09.appspot.com',
    iosBundleId: 'com.example.yesLoyality',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz9OnhdjUWbehhV5tZ-zDgslsdaRX-UkY',
    appId: '1:734665714900:web:f5fe71a7a305491d455f41',
    messagingSenderId: '734665714900',
    projectId: 'yesloyalty-97b09',
    authDomain: 'yesloyalty-97b09.firebaseapp.com',
    storageBucket: 'yesloyalty-97b09.appspot.com',
    measurementId: 'G-HBRYN9BWGL',
  );
}
